spring.datasource.url=jdbc:mysql://booxrmqq4nyfg0qr1zzk-mysql.services.clever-cloud.com:3306/bvfxes7k4mnyaqwtqqb5?useSSL=true&requireSSL=true&serverTimezone=UTC
spring.datasource.username=uxku4gzec6fmm85p
spring.datasource.password=G8qn1ejusRUmnx6XtKgq
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.maximum-pool-size=2
app.cors.allowed-origins=https://portfolio-frontend-melinda.web.app,http://localhost:4200
